---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    css: css/styles-default.css
    logo: img/tool-icon.png
runtime: shiny

---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)

# From Github
#install.packages("devtools")
#devtools::install_github("dreamRs/shinyWidgets")
library(shinyWidgets)
library(shinyjs)

# Core
library(tidyverse)
library(tidyquant)

# Interactive Visualizations
library(plotly)

# Modeling 
library(parsnip)
library(timetk)
library(xgboost)

# Fun stuff
library(ggthemes)

# Load functions
source("04_demand_forecast.R")
```

```{css}
.bootstrap-switch, .bootstrap-switch-handle-on,
.bootstrap-switch, .bootstrap-switch-handle-off,
.bootstrap-switch, .bootstrap-switch-label {
display: inline-block;
vertical-align: baseline;
}
```

```{r}
# Load data
sales_data_raw <- read_csv('sales_data_sample.csv') 
#country_codes <- read_csv("https://datahub.io/core/country-list/r/data.csv")
#country_codes <- read_csv('https://raw.githubusercontent.com/plotly/datasets/master/2014_world_gdp_with_codes.csv')

# Select relevant data
processed_data_tbl <- sales_data_raw %>% 
  select(ORDERDATE, ORDERNUMBER, ORDERLINENUMBER, COUNTRY, SALES, PRODUCTLINE, DEALSIZE, STATUS, CUSTOMERNAME)

# Preprocessing
processed_data_tbl <- processed_data_tbl %>%
  mutate(ORDERDATE = mdy_hm(ORDERDATE),
         ORDERDATE = as_datetime(ORDERDATE))

# Manual edits
processed_data_tbl$COUNTRY[processed_data_tbl$COUNTRY=="UK"] <- "United Kingdom"
processed_data_tbl$COUNTRY[processed_data_tbl$COUNTRY=="USA"] <- "United States"

```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
# Enable Shiny JS with flexdashboard (Reset = Reset + Apply)
useShinyjs(rmd = TRUE)

# Air Date Range Widget: Bug causes crash when resetting values w/ reset button
shinyWidgets::airDatepickerInput(
  inputId = "date_range",
  label = h4("Date"),
  value = c(min(processed_data_tbl$ORDERDATE),
            max(processed_data_tbl$ORDERDATE)),
  separator = " to ",
  range = TRUE,
  minDate  = min(processed_data_tbl$ORDERDATE),
  maxDate = max(processed_data_tbl$ORDERDATE),
  dateFormat = "mm-dd-yyyy",
  autoClose = TRUE,
  clearButton = TRUE,
  width = "100%",
  addon = "none"
)
  
# # Date Range Widget: DATERANGE
#  dateRangeInput(
#    inputId = "date_range",
#    label = h4("Date"),
#    start  = min(processed_data_tbl$ORDERDATE),
#    end = max(processed_data_tbl$ORDERDATE),
#    min  = min(processed_data_tbl$ORDERDATE),
#    max = max(processed_data_tbl$ORDERDATE),
#    format = "yyyy-mm-dd",
#    startview = "month")

# Double check date range widget output
#renderPrint(input$date_range)

# Picker Input Widget: COUNTRY
shinyWidgets::pickerInput(
  inputId  = "picker_country",
  label    = h4("Country"),
  choices  = sort(unique(processed_data_tbl$COUNTRY)),
  selected = unique(processed_data_tbl$COUNTRY),
  multiple = TRUE, # Allow multiple options
  options = list(
    `actions-box` = TRUE,  # Note back ticks
    size = 10,
    `selected-text-format` = "count > 3"
  )
)

# Double check picker widget output
#renderPrint(input$picker_country)

# Picker Input Widget: PRODUCTLINE
shinyWidgets::pickerInput(
  inputId  = "picker_product_line",
  label    = h4("Product"),
  choices  = sort(unique(processed_data_tbl$PRODUCTLINE)),
  selected = unique(processed_data_tbl$PRODUCTLINE),
  multiple = TRUE, # Allow multiple options
  options  = list(
    `actions-box` = TRUE,  # Note back ticks
    size = 10,
    `selected-text-format` = "count > 3"
  )
)

# Picker Input Widget: STATUS
shinyWidgets::pickerInput(
  inputId  = "picker_status",
  label    = h4("Status"),
  choices  = sort(unique(processed_data_tbl$STATUS)),
  selected = unique(processed_data_tbl$STATUS),
  multiple = TRUE, # Allow multiple options
  options  = list(
    `actions-box` = TRUE,  # Note back ticks
    size = 10,
    `selected-text-format` = "count > 3"
  )
)

# shinyWidgets::pickerInput(
#   inputId   = "picker_status", # Set input
#   label     = h4("Status"),
#   choices   = sort(unique(processed_data_tbl$STATUS)),
#   selected  = unique(processed_data_tbl$STATUS),
#   multiple = TRUE,
#   checkIcon = list(
#     yes = icon("ok", lib = "glyphicon"),
#     no  = icon("remove", lib="glyphicon")
#   ))

# Picker Input Widget: CUSTOMERNAME
shinyWidgets::pickerInput(
  inputId  = "picker_customer",
  label    = h4("Customer"),
  choices  = unique(processed_data_tbl$CUSTOMERNAME) %>% sort(),
  selected = unique(processed_data_tbl$CUSTOMERNAME) %>% sort(),
  multiple = TRUE, # Allow multiple options
  options  = list(
    `actions-box` = TRUE,  # Note back ticks
    size = 10,
    `selected-text-format` = "count > 3"
  )
)


# Checkbox Widget: DEALSIZE
shinyWidgets::checkboxGroupButtons(
  inputId   = "checkbox_deal_size", # Set input
  label     = h4("Size"),
  choices   = unique(processed_data_tbl$DEALSIZE),
  selected  = unique(processed_data_tbl$DEALSIZE),
  justified = TRUE,
  size = "sm",
  checkIcon = list(
    yes = icon("ok", lib = "glyphicon"),
    no  = icon("remove", lib="glyphicon")
  )
)


# FORECAST MODE -----
br()
hr()
br()

h4("Forecast")
shinyWidgets::switchInput(inputId = "forecast_mode",
                          handleWidth = 80,
                          labelWidth = 80,
                          inline = TRUE,
                          value = FALSE,
                          onStatus = "info",
                          onLabel = "On",
                          offLabel = "Off",
                          width = "350px")

conditionalPanel(condition = "input.forecast_mode == 1",
                 numericInput(inputId = "n_future",
                              label = "Forecast Horizon",
                              value = 12,
                              min = 1  # At least 1 period in the future
                              ))

# APPLY BUTTONS -----

# Add break 
br()
hr() # Horizontal line
br()

# Apply button
# actionButton(inputId = "apply",
#              label = "Apply",
#              icon = icon("play"))

actionButton(inputId = "apply", 
             label   = "Apply", 
             icon    = icon("play"),
             width   = '50%')

# Reset button
actionButton(inputId = "reset",
             label = "Reset",
             icon = icon("sync"),
             width   = '50%')

#style="color: #fff; background-color: #337ab7; border-color: #2e6da4"

observeEvent(eventExpr = input$reset, # When button is clicked...
             handlerExpr = {  # ...this is executed
               
               # Update Air date range widget: BROKEN
               updateAirDateInput(
                 session = session,
                 inputId = "date_range",
                 value = c(min(processed_data_tbl$ORDERDATE),
                           max(processed_data_tbl$ORDERDATE)))
               
               # # Update date range widget
               # updateDateRangeInput(
               #   session = session,
               #   inputId = "date_range",
               #   start = min(processed_data_tbl$ORDERDATE),
               #   end = max(processed_data_tbl$ORDERDATE))
               
               # Update check box widget: Deal Size
               updateCheckboxGroupButtons(
                 session = session,
                 inputId = "checkbox_deal_size",
                 selected = unique(processed_data_tbl$DEALSIZE))
               
               # Update picker widget: Country
               updatePickerInput(
                 session = session,
                 inputId = "picker_country",
                 selected = unique(processed_data_tbl$COUNTRY))
               
               # Update picker widget: Product Line
               updatePickerInput(
                 session = session,
                 inputId = "picker_product_line",
                 selected = unique(processed_data_tbl$PRODUCTLINE))
               
               # Update picker widget: Customer
               updatePickerInput(
                 session = session,
                 inputId = "picker_customer",
                 selected = unique(processed_data_tbl$CUSTOMERNAME) %>% sort())
               
               
               # Update check box widget: Status
               updatePickerInput(
                 session = session,
                 inputId = "picker_status",
                 selected = unique(processed_data_tbl$STATUS))
              
               # Update time series plot widget 
               updateRadioGroupButtons(
                 session = session,
                 inputId = "time_unit",
                 selected = "month")
               
               # Update forecast mode switch
               updateSwitchInput(
                 session = session,
                 inputId = "forecast_mode",
                 value   = FALSE)
               
               # Update numeric input
                 updateNumericInput(
                   session = session,
                   inputId = "n_future",
                   value   = 12)

               
               # Delay and Mimic click on Apply button 
              shinyjs::delay(ms = 300, expr = {
                shinyjs::click(id = "apply")
              })
               

             })
```




```{r}
# Reactive Event: waits until a button (Apply) is clicked to run reactive code 
### Tip: For performance reasons, find repetitive code and put here
processed_data_filtered_tbl <- eventReactive(
  eventExpr = input$apply, 
  
  valueExpr = {
  
    processed_data_tbl %>%
      
      # Date Range filter
      filter(ORDERDATE %>% between(left = as_datetime(input$date_range[1]),
                                    right = as_datetime(input$date_range[2]))) %>%
        
      # Checkbox filter: Deal Size
      filter(DEALSIZE %in% input$checkbox_deal_size) %>%

      # Picker filter: Country
      filter(COUNTRY %in% input$picker_country) %>%
    
      # Picker filter: Product Type
      filter(PRODUCTLINE %in% input$picker_product_line) %>%
      
      # Picker filter: Customer
      filter(CUSTOMERNAME %in% input$picker_customer) %>%
    
      # Checkbox filter: Status
      filter(STATUS %in% input$picker_status)
    
  },
  ignoreNULL = FALSE  # Don't pass data as default: run code when app loads
)
```

Row {data-height=100}
---------------------------------------------------------------

```{r}
# Healthy, Wealthy, Wise
summary_values_tbl <- reactive({
  
  processed_data_filtered_tbl() %>%
  summarise(
    order_count = unique(ORDERNUMBER) %>% length(), # Number of Orders
    total_sales= sum(SALES), # Total Revenue
    wise_metric = sum(str_detect(STATUS, "Shipped")) / 
      (length(STATUS) + 0.0001) # Pct shipped
  ) 
  # %>%
  # mutate(order_count = order_count %>% scales::number(ig.mark = ","), # Readability
  #        total_sales = total_sales %>% scales::dollar(scale = 1e-6,
  #                                                         accuracy = 0.01,
  #                                                         suffix = "M")) # Scale to thousand
})

# Verify reactivity
#renderPrint(summary_values_tbl())
```

### Order Count

```{r}
renderValueBox(

  valueBox(value   = summary_values_tbl()$order_count %>% scales::comma(),
           caption = "Orders",
           icon    = "fa-file-invoice",
           color   = case_when(summary_values_tbl()$order_count < 50 ~ "danger",
                               summary_values_tbl()$order_count < 100 ~ "warning",
                               TRUE ~ "success"))
)
```


```{r}
# renderValueBox(
# 
#   valueBox(value   = summary_values_tbl()$order_count,
#            caption = "Orders",
#            icon    = "fa-file-invoice",
#            color   = "warning")
# )
```


### Total Sales

```{r}
renderValueBox(

  valueBox(value   = summary_values_tbl()$total_sales %>% scales::dollar(scale = 1e-6, suffix="M", accuracy = 0.01),
           caption = "Sales",
           icon    = "fa-dollar-sign",
           color   = case_when(summary_values_tbl()$total_sales < 500000 ~ "danger",
                               summary_values_tbl()$total_sales < 1.5e6 ~ "warning",
                               TRUE ~ "success"))
)
```


```{r}
# renderValueBox(
# 
#   valueBox(value   = summary_values_tbl()$total_sales,
#            caption = "Sales",
#            icon    = "fa-dollar-sign",
#            color   = "success")
# )
```


### Completion Rate

```{r}
renderValueBox(

  valueBox(value   = summary_values_tbl()$wise_metric %>% scales::percent(),
           caption = "Shipped",
           icon    = "fa-truck",
           color   = case_when(summary_values_tbl()$wise_metric < 0.9 ~ "danger",
                               summary_values_tbl()$wise_metric < 0.95 ~ "warning",
                               TRUE ~ "success"))
)

```


Row {data-height=850}
---------------------------------------------------------------

### By Country {data-width=668}

```{r}
# Reactive expression based on input
geo_plot_tbl <- reactive({
  
  processed_data_filtered_tbl() %>%
    
  group_by(COUNTRY) %>%
  summarise(TOTALCOUNTRYSALES = sum(SALES)) %>%
  ungroup() %>%
  mutate(label_text = str_glue("Country: {COUNTRY}
                               Revenue: {scales::dollar(TOTALCOUNTRYSALES)}"))
})
```



```{r}
output$plotly_1 <- renderPlotly(expr = {
  
  geo_plot_tbl() %>%
  
  plot_geo(locationmode = "country names") %>%
  
  add_trace(z = ~TOTALCOUNTRYSALES,
            locations = ~COUNTRY,
            color = ~TOTALCOUNTRYSALES,
            text = ~label_text,
            marker = list(line = list(
              color = toRGB("black"), width = 0.8)), # Boundaries
            colors = "YlGnBu",
            hoverinfo = "text") %>%
  
   colorbar(title = 'Revenue',
            tickprefix = '$',
            x = 1, y = 0.8) %>% # Color Gradient
  
  layout(
    showlegend = FALSE,
    geo = list(  # Specify map options
      scope = "world",
      bgcolor = toRGB("white", alpha = 0),
      countrycolor = toRGB("gray"),
      showcountries = TRUE,
      showframe = FALSE,
      showcoastlines = FALSE,
      coastlinecolor = toRGB("#ECEFF1"),
      projection = list(type = 'Equirectangular')))
})

# Output
plotlyOutput(outputId= "plotly_1")
```


### Over Time  {data-width=332}

```{r}
# Time Unit Group buttons widget
shinyWidgets::radioGroupButtons(
  inputId   = "time_unit", # Create name 
  #label     = "Time Unit", # What is shown
  choices   = c("Day"="day","Week"="week","Month"="month","Qtr"="quarter","Year"="year"), # The options shown
  selected  = "month", # Default selection
  status    = "info", # Set color
  justified = TRUE #, # Spreads widget across window
  # checkIcon = list(
  #   yes = icon("ok", lib="glyphicon"),
  #   no = NULL # Add icon
  # )
)

# If time button is pressed, then act like Apply button is pressed
observeEvent(eventExpr = input$time_unit, {
  
  if (input$forecast_mode) {
    
    delay(300, click(id = "apply")) # Add delay and simulate clicking actions in JavaScript
    
  }
  
})

# If forecast switch is pressed, then act like Apply button is pressed...but only once
observeEvent(eventExpr = input$forecast_mode, {
  
    delay(300, click(id = "apply")) # Add delay and simulate clicking actions in JavaScript
  
}, once = TRUE)  # Code only fires once: prevents forecast from firing every time user toggles it
```


```{r}
# Reactive expression based on input
time_plot_tbl <- reactive({
  
  processed_data_filtered_tbl() %>%
    aggregate_time_series(time_unit = input$time_unit)
  
})

# Reactive event for forecast switch
time_plot_predictions_tbl <- eventReactive(eventExpr = input$apply, {
  
  if (input$forecast_mode) {
    time_plot_tbl() %>%
      generate_forecast(n_future = input$n_future, seed = 123)
  }
  
})

# renderPrint(time_plot_predictions_tbl())


# Plotly Output
output$plotly_2 <- renderPlotly({
  
  if (input$forecast_mode) {
    p <- time_plot_predictions_tbl() %>%
      plot_forecast()
  } else {
    p <- time_plot_tbl() %>%
      plot_time_series()
  }
  
  p %>%
    layout(margin = list(b = 150))

})

plotlyOutput(outputId = "plotly_2")
```

